In [126]:
'''
import data
'''

import pandas as pd

url1 = "https://raw.githubusercontent.com/kavya-desai-ds/ucla-grade-distribution/61da81e6600f66f230b48b2e74c55b4a7e1fb24d/ucla%20grades%20fall21-summer22.csv"
url2 = "https://raw.githubusercontent.com/kavya-desai-ds/ucla-grade-distribution/61da81e6600f66f230b48b2e74c55b4a7e1fb24d/ucla%20grades%20fall22-spring23.csv"
url3 = "https://raw.githubusercontent.com/kavya-desai-ds/ucla-grade-distribution/61da81e6600f66f230b48b2e74c55b4a7e1fb24d/ucla%20grades%20summer23-spring24.csv"
url4 = "https://raw.githubusercontent.com/kavya-desai-ds/ucla-grade-distribution/61da81e6600f66f230b48b2e74c55b4a7e1fb24d/ucla%20grades%20summer24-spring25.csv"

rawdf1 = pd.read_csv(url1)
rawdf2 = pd.read_csv(url2)
rawdf3 = pd.read_csv(url3)
rawdf4 = pd.read_csv(url4)

In [127]:
'''
clean df1
'''
#fix colnames
cleandf1 = rawdf1.drop(columns=['ENROL TERM SEQ NBR', 'INTL CATL', 'INTL SECT', 'CREATION DATE', 'ROWNO'])
new_col_names = ['Enrollment Term', 'Subject Area', 'Catalogue Number', 'Section Number', 'Letter Grade',
       'Letter Grade Count', 'Total Enrolled', 'Instructor Name', 'Instructor Code', 'Course Title']
cleandf1.columns = new_col_names

#remove classes not taught by a prof
cleandf1 = cleandf1.loc[cleandf1['Instructor Code'] == 1]
cleandf1 = cleandf1.drop(columns=['Instructor Code'])

#remove non-letter grades like P/NP, etc.
grades_to_keep = ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F']
cleandf1['Letter Grade'] = cleandf1['Letter Grade'].str.strip()
cleandf1 = cleandf1.loc[cleandf1['Letter Grade'].isin(grades_to_keep)]

#create new col with numeric gpa instead of letter grade
letter_to_gpa = {
    "A+" : 4.0,
    "A" : 4.0,
    "A-" : 3.7,
    "B+" : 3.3,
    "B" : 3.0,
    "B-" : 2.7,
    "C+" : 2.3,
    "C" : 2.0,
    "C-" : 1.7,
    "D+" : 1.3,
    "D" : 1.0,
    "D-" : 0.7,
    "F" : 0.0
}

cleandf1["Numeric Grade"] = cleandf1["Letter Grade"].map(lambda row: letter_to_gpa[row])

#enrollment term fix
enrollment_year = {
    "21F" : 2021,
    "22W" : 2022,
    "22S" : 2022,
    "221" : 2022,
    "222" : 2022
}
enrollment_q = {
    "21F" : "Fall",
    "22W" : "Winter",
    "22S" : "Spring",
    "221" : "Summer",
    "222" : "Summer"
}

cleandf1["Year"] = cleandf1["Enrollment Term"].map(lambda row: enrollment_year[row])
cleandf1["Quarter"] = cleandf1["Enrollment Term"].map(lambda row: enrollment_q[row])
cleandf1.head()

,Enrollment Term,Subject Area,Catalogue Number,Section Number,Letter Grade,Letter Grade Count,Total Enrolled,Instructor Name,Course Title,Numeric Grade,Year,Quarter
0,21F,A&O SCI,1,1,A+,12,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,4.0,2021,Fall
1,21F,A&O SCI,1,1,A,17,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,4.0,2021,Fall
2,21F,A&O SCI,1,1,A-,9,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.7,2021,Fall
3,21F,A&O SCI,1,1,B+,9,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.3,2021,Fall
4,21F,A&O SCI,1,1,B,8,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.0,2021,Fall

In [128]:
'''
clean df2
'''
#fix colnames
cleandf2 = rawdf2.drop(columns=['ENROL TERM SEQ NBR', 'INTL CATL', 'INTL SECT', 'CREATION DATE', 'ROWNO'])
new_col_names = ['Enrollment Term', 'Subject Area', 'Catalogue Number', 'Section Number', 'Letter Grade',
       'Letter Grade Count', 'Total Enrolled', 'Instructor Name', 'Instructor Code', 'Course Title']
cleandf2.columns = new_col_names


#remove classes not taught by a prof
cleandf2 = cleandf2.loc[cleandf2['Instructor Code'] == 1]
cleandf2 = cleandf2.drop(columns=['Instructor Code'])

#remove non-letter grades like P/NP, etc.
grades_to_keep = ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F']
cleandf2['Letter Grade'] = cleandf2['Letter Grade'].str.strip()
cleandf2 = cleandf2.loc[cleandf2['Letter Grade'].isin(grades_to_keep)]

#create new col with numeric gpa instead of letter grade
letter_to_gpa = {
    "A+" : 4.0,
    "A" : 4.0,
    "A-" : 3.7,
    "B+" : 3.3,
    "B" : 3.0,
    "B-" : 2.7,
    "C+" : 2.3,
    "C" : 2.0,
    "C-" : 1.7,
    "D+" : 1.3,
    "D" : 1.0,
    "D-" : 0.7,
    "F" : 0.0
}

cleandf2["Numeric Grade"] = cleandf2["Letter Grade"].map(lambda row: letter_to_gpa[row])

#enrollment term fix
enrollment_year = {
    "22F" : 2022,
    "23W" : 2023,
    "23S" : 2023
}
enrollment_q = {
    "22F" : "Fall",
    "23W" : "Winter",
    "23S" : "Spring"
}

cleandf2["Year"] = cleandf2["Enrollment Term"].map(lambda row: enrollment_year[row])
cleandf2["Quarter"] = cleandf2["Enrollment Term"].map(lambda row: enrollment_q[row])
cleandf2.head()

,Enrollment Term,Subject Area,Catalogue Number,Section Number,Letter Grade,Letter Grade Count,Total Enrolled,Instructor Name,Course Title,Numeric Grade,Year,Quarter
0,22F,A&O SCI,1,1,A+,6,110,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,4.0,2022,Fall
1,22F,A&O SCI,1,1,A,19,110,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,4.0,2022,Fall
2,22F,A&O SCI,1,1,A-,14,110,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.7,2022,Fall
3,22F,A&O SCI,1,1,B+,10,110,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.3,2022,Fall
4,22F,A&O SCI,1,1,B,12,110,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.0,2022,Fall

In [129]:
'''
clean df3
'''
#fix colnames
cleandf3 = rawdf3
cleandf3['subj_area_name'] = cleandf3['subj_area_cd']
cleandf3 = cleandf3.drop(columns=['subj_area_cd', 'crs_catlg_no', 'sect_no'])
new_col_names = ['Enrollment Term', 'Subject Area', 'Catalogue Number', 'Section Number', 'Letter Grade',
       'Letter Grade Count', 'Total Enrolled', 'Instructor Name', 'Instructor Code', 'Course Title']
cleandf3.columns = new_col_names
cleandf3.head()

#remove classes not taught by a prof
cleandf3 = cleandf3.loc[cleandf3['Instructor Code'] == 1]
cleandf3 = cleandf3.drop(columns=['Instructor Code'])

#remove non-letter grades like P/NP, etc.
grades_to_keep = ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F']
cleandf3['Letter Grade'] = cleandf3['Letter Grade'].str.strip()
cleandf3 = cleandf3.loc[cleandf3['Letter Grade'].isin(grades_to_keep)]

#create new col with numeric gpa instead of letter grade
letter_to_gpa = {
    "A+" : 4.0,
    "A" : 4.0,
    "A-" : 3.7,
    "B+" : 3.3,
    "B" : 3.0,
    "B-" : 2.7,
    "C+" : 2.3,
    "C" : 2.0,
    "C-" : 1.7,
    "D+" : 1.3,
    "D" : 1.0,
    "D-" : 0.7,
    "F" : 0.0
}

cleandf3["Numeric Grade"] = cleandf3["Letter Grade"].map(lambda row: letter_to_gpa[row])

#enrollment term fix
enrollment_year = {
    "23F" : 2023,
    "24W" : 2024,
    "24S" : 2024,
    "231" : 2023,
    "232" : 2023
}
enrollment_q = {
    "23F" : "Fall",
    "24W" : "Winter",
    "24S" : "Spring",
    "231" : "Summer",
    "232" : "Summer"
}

cleandf3["Year"] = cleandf3["Enrollment Term"].map(lambda row: enrollment_year[row])
cleandf3["Quarter"] = cleandf3["Enrollment Term"].map(lambda row: enrollment_q[row])
cleandf3.head()

,Enrollment Term,Subject Area,Catalogue Number,Section Number,Letter Grade,Letter Grade Count,Total Enrolled,Instructor Name,Course Title,Numeric Grade,Year,Quarter
1,231,A&O SCI,2,1,A+,12,25,"GONZALEZ, DAVID",Air Pollution,4.0,2023,Summer
2,231,A&O SCI,2,1,A,5,25,"GONZALEZ, DAVID",Air Pollution,4.0,2023,Summer
4,231,A&O SCI,2,1,A-,4,25,"GONZALEZ, DAVID",Air Pollution,3.7,2023,Summer
5,231,A&O SCI,2,1,B+,1,25,"GONZALEZ, DAVID",Air Pollution,3.3,2023,Summer
6,231,A&O SCI,2,1,C,1,25,"GONZALEZ, DAVID",Air Pollution,2.0,2023,Summer

In [130]:
'''
clean df4
'''
#fix colnames
cleandf4 = rawdf4
cleandf4['subj_area_name'] = cleandf4['subj_area_cd']
cleandf4 = cleandf4.drop(columns=['subj_area_cd', 'crs_catlg_no', 'sect_no'])
new_col_names = ['Enrollment Term', 'Subject Area', 'Catalogue Number', 'Section Number', 'Letter Grade',
       'Letter Grade Count', 'Total Enrolled', 'Instructor Name', 'Instructor Code', 'Course Title']
cleandf4.columns = new_col_names
cleandf4.head()

#remove classes not taught by a prof
cleandf4 = cleandf4.loc[cleandf4['Instructor Code'] == 1]
cleandf4 = cleandf4.drop(columns=['Instructor Code'])

#remove non-letter grades like P/NP, etc.
grades_to_keep = ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-', 'F']
cleandf4['Letter Grade'] = cleandf4['Letter Grade'].str.strip()
cleandf4 = cleandf4.loc[cleandf4['Letter Grade'].isin(grades_to_keep)]

#create new col with numeric gpa instead of letter grade
letter_to_gpa = {
    "A+" : 4.0,
    "A" : 4.0,
    "A-" : 3.7,
    "B+" : 3.3,
    "B" : 3.0,
    "B-" : 2.7,
    "C+" : 2.3,
    "C" : 2.0,
    "C-" : 1.7,
    "D+" : 1.3,
    "D" : 1.0,
    "D-" : 0.7,
    "F" : 0.0
}

cleandf4["Numeric Grade"] = cleandf4["Letter Grade"].map(lambda row: letter_to_gpa[row])

#enrollment term fix
enrollment_year = {
    "24F" : 2024,
    "25W" : 2025,
    "25S" : 2025,
    "241" : 2024,
    "242" : 2024
}
enrollment_q = {
    "24F" : "Fall",
    "25W" : "Winter",
    "25S" : "Spring",
    "241" : "Summer",
    "242" : "Summer"
}

cleandf4["Year"] = cleandf4["Enrollment Term"].map(lambda row: enrollment_year[row])
cleandf4["Quarter"] = cleandf4["Enrollment Term"].map(lambda row: enrollment_q[row])
cleandf4.head()

,Enrollment Term,Subject Area,Catalogue Number,Section Number,Letter Grade,Letter Grade Count,Total Enrolled,Instructor Name,Course Title,Numeric Grade,Year,Quarter
0,241,A&O SCI,2,2,A+,18,27,"GONZALEZ, DAVID",Air Pollution,4.0,2024,Summer
1,241,A&O SCI,2,2,A,5,27,"GONZALEZ, DAVID",Air Pollution,4.0,2024,Summer
2,241,A&O SCI,2,2,A-,2,27,"GONZALEZ, DAVID",Air Pollution,3.7,2024,Summer
3,241,A&O SCI,2,2,B,1,27,"GONZALEZ, DAVID",Air Pollution,3.0,2024,Summer
4,241,A&O SCI,2,2,F,1,27,"GONZALEZ, DAVID",Air Pollution,0.0,2024,Summer

In [132]:
'''
combine data
'''

finaldf = pd.concat([cleandf1, cleandf2, cleandf3, cleandf4])

#quarter sequence identifier (for easy graphing)
q_to_num = {
    "Winter" : 1,
    "Spring" : 2,
    "Summer" : 3,
    "Fall" : 4
}

finaldf["Quarter Order"] = finaldf["Quarter"].map(lambda row: q_to_num[row])
finaldf.head()

,Enrollment Term,Subject Area,Catalogue Number,Section Number,Letter Grade,Letter Grade Count,Total Enrolled,Instructor Name,Course Title,Numeric Grade,Year,Quarter,Quarter Order
0,21F,A&O SCI,1,1,A+,12,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,4.0,2021,Fall,4
1,21F,A&O SCI,1,1,A,17,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,4.0,2021,Fall,4
2,21F,A&O SCI,1,1,A-,9,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.7,2021,Fall,4
3,21F,A&O SCI,1,1,B+,9,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.3,2021,Fall,4
4,21F,A&O SCI,1,1,B,8,93,"BIANCHI, DANIELE",Climate Change: From Puzzles to Policy,3.0,2021,Fall,4

In [133]:
'''
save the clean csv and have fun!
'''
finaldf.to_csv("clean_ucla_grade_dist.csv", index=False)